version: 2.1
orbs:
  docker: circleci/docker@2.1.3
  github-cli: circleci/github-cli@2.1.0
jobs:
  gh-install:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - github-cli/install
  clone:
    docker:
      - image: cimg/base:stable
    steps:
      - github-cli/clone
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - docker/build:
          dockerfile: Dockerfile 
          image: ku-cloud-serve 
          path: ./src/KuCloud.Api
          tag: latest 
  push:
    docker:
      - image: cimg/base:stable
    steps:
      - docker/push:
          image: ku-cloud-serve 
          registry: $REGISTRY_URL 
          tag: latest 
workflows:
  example-workflow:
    jobs:
      - gh-install
      - clone:
          requires:
            - gh-install
      - build:
          requires:
            - clone
      - push:
          requires:
            - build